In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('ai_dev_productivity.csv')

In [3]:
data

,hours_coding,coffee_intake_mg,distractions,sleep_hours,commits,bugs_reported,ai_usage_hours,cognitive_load,task_success
0,5.99,600,1,5.8,2,1,0.71,5.4,1
1,4.72,568,2,6.9,5,3,1.75,4.7,1
2,6.30,560,1,8.9,2,0,2.27,2.2,1
3,8.05,600,7,6.3,9,5,1.40,5.9,0
4,4.53,421,6,6.9,4,0,1.26,6.3,1
...,...,...,...,...,...,...,...,...,...
495,6.08,594,1,5.3,3,0,0.91,6.8,1
496,2.93,382,2,6.7,3,2,1.38,5.9,0
497,4.62,494,4,7.5,2,0,0.41,4.5,1
498,3.25,296,6,6.9,1,0,1.52,6.3,0
499,2.23,252,4,8.8,0,0,1.05,2.6,0

In [4]:
data.isnull().sum()

hours_coding        0
coffee_intake_mg    0
distractions        0
sleep_hours         0
commits             0
bugs_reported       0
ai_usage_hours      0
cognitive_load      0
task_success        0
dtype: int64

In [5]:
data.duplicated().sum()

np.int64(0)

In [6]:
data.describe()

,hours_coding,coffee_intake_mg,distractions,sleep_hours,commits,bugs_reported,ai_usage_hours,cognitive_load,task_success
count,500.000000,500.000000,500.000000,500.000000,500.00000,500.000000,500.000000,500.000000,500.000000
mean,5.015600,463.192000,2.976000,6.975800,4.60800,0.858000,1.510920,4.498200,0.606000
std,1.947253,142.334991,1.678409,1.455965,2.70499,1.102846,1.085557,1.868861,0.489124
min,0.000000,6.000000,0.000000,3.000000,0.00000,0.000000,0.000000,1.000000,0.000000
25%,3.600000,369.500000,2.000000,6.100000,3.00000,0.000000,0.697500,3.175000,0.000000
50%,5.030000,500.500000,3.000000,6.950000,5.00000,0.000000,1.260000,4.400000,1.000000
75%,6.275000,600.000000,4.000000,7.900000,6.00000,2.000000,2.070000,5.800000,1.000000
max,12.000000,600.000000,8.000000,10.000000,13.00000,5.000000,6.360000,10.000000,1.000000

# Feature Scaling

In [7]:
from sklearn.preprocessing import StandardScaler
scale = StandardScaler()

In [8]:
data[['hours_coding', 'coffee_intake_mg', 'distractions', 'sleep_hours','commits', 'bugs_reported', 'ai_usage_hours']] = scale.fit_transform(data[['hours_coding', 'coffee_intake_mg', 'distractions', 'sleep_hours','commits', 'bugs_reported', 'ai_usage_hours']])

In [9]:
X = data.drop(columns = ['cognitive_load'])
y = data['cognitive_load']

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2, random_state = 42)

In [11]:
X.head()

,hours_coding,coffee_intake_mg,distractions,sleep_hours,commits,bugs_reported,ai_usage_hours,task_success
0,0.500898,0.962132,-1.178484,-0.808383,-0.965110,0.128887,-0.738535,1
1,-0.151956,0.737085,-0.582085,-0.052114,0.145063,1.944193,0.220458,1
2,0.660256,0.680823,-1.178484,1.322921,-0.965110,-0.778767,0.699954,1
3,1.559858,0.962132,2.399909,-0.464624,1.625292,3.759500,-0.102280,0
4,-0.249627,-0.296724,1.803510,-0.052114,-0.224995,-0.778767,-0.231375,1

In [13]:
y

0      5.4
1      4.7
2      2.2
3      5.9
4      6.3
      ...
495    6.8
496    5.9
497    4.5
498    6.3
499    2.6
Name: cognitive_load, Length: 500, dtype: float64

In [20]:
import tensorflow
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping

In [18]:
model = Sequential([Dense(64,input_shape = (X_train.shape[1],),activation = 'linear'),
                    Dense(32, activation = 'linear'),
                    Dense(1,activation = 'linear')
                    ])

d:\Praticals\Generative AI\Deep Learning\TitanicProject\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [19]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           576 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,689 (10.50 KB)

 Trainable params: 2,689 (10.50 KB)

 Non-trainable params: 0 (0.00 B)

In [22]:
model.compile(optimizer = 'adam',metrics = ['mae'],loss = 'mse')

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [23]:
model.fit(X_train,y_train,epochs = 100)

Epoch 1/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 21.4459 - mae: 4.1836
Epoch 2/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 15.4372 - mae: 3.5660
Epoch 3/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.2159 - mae: 2.8402
Epoch 4/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5.9918 - mae: 2.0516
Epoch 5/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3.5264 - mae: 1.4879
Epoch 6/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.7630 - mae: 1.3309
Epoch 7/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.6141 - mae: 1.2962
Epoch 8/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.4835 - mae: 1.2677
Epoch 9/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.3203 - mae: 1.2175
Epoch 10/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.1998 - mae: 1.1917
Epoch 11/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.1220 - mae: 1.1726
Epoch 12/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.0014 - mae: 1.1423
Epoch 13/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.8926 - mae: 1.1093
Epoch 14/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.8072 - mae: 1.0851
Epoch 15/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.7009 - mae: 1.0553
Epoch 16/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.6139 - mae: 1.0333
Epoch 17/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.5341 - mae: 1.0086
Epoch 18/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.4845 - mae: 0.9820
Epoch 19/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.4080 - mae: 0.9576
Epoch 20/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.3414 - mae: 0.9364
Epoch 21/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.2716 - mae: 0.9044
Epoch 22/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.2129 - mae: 0.8827
Epoch 23/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.1752 - mae: 0.8702
Epoch 24/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.1354 - mae: 0.8541
Epoch 25/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.1077 - mae: 0.8361
Epoch 26/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.0899 - mae: 0.8289
Epoch 27/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.0676 - mae: 0.8234
Epoch 28/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.0470 - mae: 0.8087
Epoch 29/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.0177 - mae: 0.7977
Epoch 30/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.0116 - mae: 0.7958
Epoch 31/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.0426 - mae: 0.8027
Epoch 32/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.0275 - mae: 0.8058
Epoch 33/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9804 - mae: 0.7844
Epoch 34/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.0034 - mae: 0.7963
Epoch 35/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.0042 - mae: 0.7907
Epoch 36/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.0017 - mae: 0.7967
Epoch 37/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.0026 - mae: 0.7972
Epoch 38/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9811 - mae: 0.7864
Epoch 39/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9932 - mae: 0.7873
Epoch 40/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.0001 - mae: 0.7908
Epoch 41/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.9790 - mae: 0.7800
Epoch 42/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9737 - mae: 0.7827
Epoch 43/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9770 - mae: 0.7861
Epoch 44/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.9861 - mae: 0.7828
Epoch 45/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9986 - mae: 0.7900
Epoch 46/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9846 - mae: 0.7856
Epoch 47/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9912 - mae: 0.7863
Epoch 48/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.9901 - mae: 0.7867
Epoch 49/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9833 - mae: 0.7848
Epoch 50/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.0096 - mae: 0.7973
Epoch 51/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9847 - mae: 0.7836
Epoch 52/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.9779 - mae: 0.7824
Epoch 53/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.0011 - mae: 0.7949
Epoch 54/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9790 - mae: 0.7861
Epoch 55/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.9801 - mae: 0.7874
Epoch 56/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9748 - mae: 0.7819
Epoch 57/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9996 - mae: 0.7932
Epoch 58/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9938 - mae: 0.7900
Epoch 59/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.9691 - mae: 0.7787
Epoch 60/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.9839 - mae: 0.7843
Epoch 61/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9999 - mae: 0.7905
Epoch 62/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9789 - mae: 0.7801
Epoch 63/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9853 - mae: 0.7871
Epoch 64/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9878 - mae: 0.7903
Epoch 65/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.0020 - mae: 0.7898
Epoch 66/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.0077 - mae: 0.8039
Epoch 67/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.0002 - mae: 0.7889
Epoch 68/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.9903 - mae: 0.7873
Epoch 69/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9746 - mae: 0.7826
Epoch 70/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9952 - mae: 0.7897
Epoch 71/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.0182 - mae: 0.7983
Epoch 72/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.9991 - mae: 0.7912
Epoch 73/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.9814 - mae: 0.7836
Epoch 74/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9793 - mae: 0.7871
Epoch 75/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9897 - mae: 0.7894
Epoch 76/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.9827 - mae: 0.7824
Epoch 77/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.9908 - mae: 0.7910
Epoch 78/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9851 - mae: 0.7872
Epoch 79/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9861 - mae: 0.7877
Epoch 80/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.0227 - mae: 0.7995
Epoch 81/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9924 - mae: 0.7867
Epoch 82/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9866 - mae: 0.7856
Epoch 83/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9794 - mae: 0.7846
Epoch 84/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9830 - mae: 0.7881
Epoch 85/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9956 - mae: 0.7815
Epoch 86/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9887 - mae: 0.7837
Epoch 87/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9900 - mae: 0.7896
Epoch 88/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9844 - mae: 0.7880
Epoch 89/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.0124 - mae: 0.7928
Epoch 90/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9874 - mae: 0.7898
Epoch 91/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9839 - mae: 0.7856
Epoch 92/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.9858 - mae: 0.7895
Epoch 93/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.0038 - mae: 0.7967
Epoch 94/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9999 - mae: 0.7901
Epoch 95/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9796 - mae: 0.7852
Epoch 96/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.9897 - mae: 0.7876
Epoch 97/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.9864 - mae: 0.7910
Epoch 98/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.9878 - mae: 0.7878
Epoch 99/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.0115 - mae: 0.8053
Epoch 100/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9964 - mae: 0.7917

In [25]:
from sklearn.metrics import mean_squared_error

In [26]:
y_predict = model.predict(X_test)

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step

In [27]:
mean_squared_error(y_predict,y_test)

0.8645765754385206