# Text Cleaning
### STEP 1: lowercasing

In [190]:
import pandas as pd

In [191]:
d = pd.read_csv('train_data_cleaning.csv')

In [192]:
d.head()

,id,keyword,location,text,target
0,1,NaN,NaN,Our Deeds are the Reason of this # earthquake...,1
1,4,NaN,NaN,Forest fire near La Ronge Sask . Canada,1
2,5,NaN,NaN,All residents asked to ' shelter in place ' ...,1
3,6,NaN,NaN,"13,000 people receive # wildfires evacuation ...",1
4,7,NaN,NaN,Just got sent this photo from Ruby # Alaska a...,1

In [193]:
d['text'][0]

'Our Deeds are the Reason of this  # earthquake May ALLAH Forgive us all'

In [194]:
d['text'] = d['text'].str.lower()
d['text'][0]

'our deeds are the reason of this  # earthquake may allah forgive us all'

## Dirty Data:
#### --> HTML Tags
#### --> URLs
#### --> Punctuations
#### -->

In [195]:
text = '<h1> Hello Mera Naam Geetanshu Hai </h1>'

In [196]:
import re

re.sub(r'<.*?>','',text)

' Hello Mera Naam Geetanshu Hai '

In [197]:
data = pd.DataFrame({'col':['Hello <h1> I am Geetanshu Singh Rajawat</h1>','<a href = www.google.com> Click Here </a>','<p> How Are you </p>']})

In [198]:
data

                                            col
0  Hello <h1> I am Geetanshu Singh Rajawat</h1>
1     <a href = www.google.com> Click Here </a>
2                          <p> How Are you </p>

In [199]:
def html_removal(text):
    empty_html = []
    for i in text:
        empty_html.append(re.sub(r'<.*?>','',i))
    return empty_html

In [200]:
data.apply(html_removal)

                                   col
0  Hello  I am Geetanshu Singh Rajawat
1                          Click Here
2                         How Are you

In [201]:
d1 = pd.read_csv('topic_classification_data.csv')

In [202]:
d1['content'][1]

"NEW: Modi's promise to ban plastic straws this month put India in the lead in the region for curbing pollution. But many beverage makers aren't ready.  https://t.co/v6hhnenb2t"

In [203]:
d1['content'].isnull().sum()

np.int64(5)

In [204]:
d1.dropna(subset = ['content'], inplace = True)

In [205]:
d1['content'].isnull().sum()

np.int64(0)

In [206]:
d1['content'] = d1['content'].astype('str')

### STEP 2: Removing URLs

In [207]:
text = 'Hey https://geetanshusingh.com visit my website'

In [208]:
re.sub(r'https?://\S+|www\.\S+','',text)

'Hey  visit my website'

In [209]:
def url_remover(text):
    return (re.sub(r'https?://\S+|www\.\S+','',text))

In [210]:
d1['content'] = d1['content'].apply(url_remover)

In [211]:
d1['content'][1]

"NEW: Modi's promise to ban plastic straws this month put India in the lead in the region for curbing pollution. But many beverage makers aren't ready.  "

# Removing Punctuations

In [212]:
text = "hey, My name is Geetanshu! Ho.w are you?"

In [213]:
re.sub(r'[^\w\s]','',text)

'hey My name is Geetanshu How are you'

In [214]:
def punctuations_removal(text):
    return re.sub(r'[^\w\s]','',text)

In [215]:
d1['content']

0         I'm struggling to understand how I feel about ...
1         NEW: Modi's promise to ban plastic straws this...
2         SURVEY: Middle-Income Americans Spending Less ...
3         WATCH: Wall Street ended lower after bank stoc...
4         Someone selling a ton of $SE puts to open Sep ...
                                ...
136798    Ehlers-Danlos syndrome (EDS) is a group of inh...
136799    i feel tortured being a person because no one ...
136800    Aicardi-Goutieres syndrome is an inherited con...
136801    i feel really successful for the fact that i r...
136802    i feel that youve got to be fearless as an art...
Name: content, Length: 136798, dtype: object

In [216]:
d1['content'].apply(punctuations_removal)

0         Im struggling to understand how I feel about s...
1         NEW Modis promise to ban plastic straws this m...
2         SURVEY MiddleIncome Americans Spending Less Am...
3         WATCH Wall Street ended lower after bank stock...
4         Someone selling a ton of SE puts to open Sep a...
                                ...
136798    EhlersDanlos syndrome EDS is a group of inheri...
136799    i feel tortured being a person because no one ...
136800    AicardiGoutieres syndrome is an inherited cond...
136801    i feel really successful for the fact that i r...
136802    i feel that youve got to be fearless as an art...
Name: content, Length: 136798, dtype: object

In [217]:
slang_dictionary = {'asap':'as soon as possible','gm':'Good Morning','lol':'laugh out loud','gn':'Good Night','fomo':'fear of missing out','yolo':'You only live once','lmao':'laughing my ass out'}

In [218]:
slang = pd.DataFrame({'slang':['Hey call me asap','hello gm','lol that was funny','hey yolo, you know it','having fomo']})
text = 'Hey call me asap , hello gm , lol that was funny'

In [219]:
def expand_slang(text,slang_dict):
    words = text.split()
    return ' '.join([slang_dict.get(word,word) for word in words])

In [220]:
expand_slang(text,slang_dictionary)

'Hey call me as soon as possible , hello Good Morning , laugh out loud that was funny'

In [221]:
# pip install textblob

# STOPWORDS REMOVAL

In [222]:
from textblob import TextBlob

In [223]:
from nltk.corpus import stopwords

In [224]:
english_stopwords = stopwords.words('english')

In [225]:
text = 'Hey how are you i am fine i was looking for you .'

In [226]:
without_stops= []
for i in text.split():
    if i in english_stopwords:
        without_stops.append('')
    else:
        without_stops.append(i)
    x=without_stops[:]
    ' '.join(x)

In [227]:
x

['Hey', '', '', '', '', '', 'fine', '', '', 'looking', '', '', '.']

In [233]:
d1 = pd.read_csv('topic_classification_data.csv')

In [235]:
d1.dropna(inplace = True)

In [236]:
d1['content'].isnull().sum()

np.int64(0)

In [240]:
def stopwords(text):
    li= []
    for i in text.split():
        if i in english_stopwords:
            li.append("")
        else:
            li.append(i)
    x=li[:]
    li.clear()
    return " ".join(x)

In [242]:
d1['content'] = d1['content'].apply(stopwords)

# HANDLING EMOJIES

### DELETING/REMOVING EMOJIES

In [247]:
def remove_emojis(text):
    emoji_pattern = re.compile(
        "["
        u"\U0001F600-\U0001F64F"    #EMOTICONS
        u"\U0001F300-\U0001F5FF"    #SYMBOLS & PICTOGRAPHS
        u"\U0001F680-\U0001F6FF"    #TRANSPORT & MAP SYMBOLS
        u"\U0001F1E0-\U0001F1FF"
        "]+",
        flags = re.UNICODE
    )
    return emoji_pattern.sub(r'',text)

In [244]:
data = {
    'content': [
        'I Love Pizza 🍕 So much!',
        'Good Morning 😁 👌',
        'lets go for 🫂 a ride 🦶',
        'vacation time 🤞',
        'Happy 😈 Birthday',
        '🙅‍♂️ Felling Strong'
    ]
}
data = pd.DataFrame(data)

In [248]:
data['content'].apply(remove_emojis)

0    I Love Pizza  So much!
1            Good Morning
2    lets go for 🫂 a ride 🦶
3           vacation time 🤞
4           Happy  Birthday
5        ‍♂️ Felling Strong
Name: content, dtype: object

In [ ]:
# pip install emoji

Collecting emoji
  Using cached emoji-2.15.0-py3-none-any.whl.metadata (5.7 kB)
Using cached emoji-2.15.0-py3-none-any.whl (608 kB)
Installing collected packages: emoji
Successfully installed emoji-2.15.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [251]:
import emoji

## REPLACING EMOJIES

In [257]:
def replace_emoji(text):
    return emoji.demojize(text,delimiters = (" "," "))

In [258]:
data['content'].apply(replace_emoji)

0                        I Love Pizza  pizza  So much!
1    Good Morning  beaming_face_with_smiling_eyes  ...
2           lets go for  people_hugging  a ride  foot
3                      vacation time  crossed_fingers
4             Happy  smiling_face_with_horns  Birthday
5                     man_gesturing_NO  Felling Strong
Name: content, dtype: object