In [61]:
import pandas as pd

In [62]:
bank = pd.read_csv('Bank_Marketing_Original_Data.csv')

In [63]:
bank.head()

,Age,Job,Marital,Education,Default,Balance,Housing,Loan,contact,Day,Month,Duration,Campaign,Pdays,Previous,poutcome,TARGET
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no

In [64]:
bank['Job'].value_counts()

Job
blue-collar      9732
management       9458
technician       7597
admin.           5171
services         4154
retired          2264
self-employed    1579
entrepreneur     1487
unemployed       1303
housemaid        1240
student           938
unknown           288
Name: count, dtype: int64

### There's no order in the job field this is why we will use nominal encoding on this one

In [65]:
bank['Education'].value_counts()

Education
secondary    23202
tertiary     13301
primary       6851
unknown       1857
Name: count, dtype: int64

## There's an order in Education field this is why we will use ordinal encoding
#### tertiary > Secondary > Primary > Unknown

# Input data must be in 2D Format
###
### Ordinal Encoder ---> Education
### Label Encoder ---> Target
### Nominal Encoder ---> Married, ...

# Ordinal Encoder

In [66]:
ordinal_data = bank[['Education']]

In [67]:
from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder(categories = [['unknown', 'primary', 'secondary', 'tertiary' ]])

ordinal_data = oe.fit_transform(ordinal_data)

In [68]:
ordinal_data

array([[3.],
       [2.],
       [2.],
       ...,
       [2.],
       [2.],
       [2.]])

# Label Encoder

In [69]:
target_data = bank[['TARGET']]
# , 'Default', 'Housing', 'Loan'

In [70]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

target_data = le.fit_transform(target_data)

c:\Users\geeta\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [71]:
target_data

array([0, 0, 0, ..., 1, 0, 0])

In [72]:
bank

,Age,Job,Marital,Education,Default,Balance,Housing,Loan,contact,Day,Month,Duration,Campaign,Pdays,Previous,poutcome,TARGET
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,51,technician,married,tertiary,no,825,no,no,cellular,17,nov,977,3,-1,0,unknown,yes
45207,71,retired,divorced,primary,no,1729,no,no,cellular,17,nov,456,2,-1,0,unknown,yes
45208,72,retired,married,secondary,no,5715,no,no,cellular,17,nov,1127,5,184,3,success,yes
45209,57,blue-collar,married,secondary,no,668,no,no,telephone,17,nov,508,4,-1,0,unknown,no
45210,37,entrepreneur,married,secondary,no,2971,no,no,cellular,17,nov,361,2,188,11,other,no

In [73]:
bank['Loan'].value_counts()

Loan
no     37967
yes     7244
Name: count, dtype: int64

# Nominal Encoder

In [76]:
nominal_data = bank[['Job', 'Marital', 'contact', 'Month', 'poutcome']]
#nominal_data

In [78]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()
nominal_data = ohe.fit_transform(nominal_data)

In [79]:
nominal_data

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 226055 stored elements and shape (45211, 34)>